/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouterImport } from './routes/AppRouter'

// Create/Update Routes

const AppRouterRoute = AppRouterImport.update({
  path: '/AppRouter',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/AppRouter': {
      preLoaderRoute: typeof AppRouterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([AppRouterRoute])

/* prettier-ignore-end */
